# Generated by Django 6.0.6 on 2026-06-23 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Essay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kicker', models.CharField(default='Introduction · An Essay', help_text="Small label above the title, e.g. 'Introduction · An Essay'.", max_length=120)),
                ('title', models.CharField(max_length=200)),
                ('deck', models.TextField(blank=True, help_text='Subtitle / standfirst shown in italics below the title.')),
                ('author_name', models.CharField(blank=True, max_length=120)),
                ('author_title', models.CharField(blank=True, help_text="e.g. 'Professor of History, George Mason University'.", max_length=200)),
                ('author_bio', models.TextField(blank=True)),
                ('body', models.TextField(help_text="Markdown. Use '## ' for section headings, '> ' for pull quotes, and '[^1]' footnote references (defined as '[^1]: text' at the bottom) for the Notes section.")),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Essay',
                'verbose_name_plural': 'Essay',
            },
        ),
    ]
