# Generated by Django 6.0.6 on 2026-06-23 16:14

from django.db import migrations

ESSAY_BODY = """\
In the first decades of the Commonwealth, a Virginian with a grievance, a claim, or a debt owed by the state had one reliable instrument: the petition. Addressed to the General Assembly and read aloud in committee, it was at once a legal document and a piece of plain speech — a formal appeal that nonetheless carried the cadence of an individual standing before the state, asking to be counted.[^1]

## A bureaucracy of voices

To read these documents in bulk is to hear a young republic working out who belonged to it. The petitions are formulaic, and that is precisely their value: the formula reveals what the state expected its citizens to sound like, and the deviations reveal who struggled to meet that expectation.

> The petition is the place where private trouble is translated into public language — and not everyone was permitted to do the translating.

Enslaved Virginians appear throughout these pages, almost never as authors and almost always as subjects: counted as property in claims for compensation, named in contests over wills, invoked in protests against manumission. Their presence in a record built to exclude them is one of the collection's most difficult and necessary lessons.[^2]

What follows — the catalogue, the map, the search — is an invitation to listen closely to a chorus of ordinary people who believed, with reason and sometimes against it, that the state was theirs to address.

[^1]: [Citation to be supplied by the author.]

[^2]: [Citation to be supplied by the author.]
"""


def create_essay(apps, schema_editor):
    Essay = apps.get_model("pages", "Essay")
    if Essay.objects.exists():
        return
    Essay.objects.create(
        kicker="Introduction · An Essay",
        title="The Grammar of Appeal",
        deck=(
            "How ordinary Virginians learned to address their government — and "
            "what their petitions and pension claims still ask of us."
        ),
        author_name="[Author Name]",
        author_title="Professor of History, [Institution]",
        author_bio=(
            "[A short biography of the author — field of study, current "
            "position, and relevant publications — to be supplied.]"
        ),
        body=ESSAY_BODY,
    )


def remove_essay(apps, schema_editor):
    Essay = apps.get_model("pages", "Essay")
    Essay.objects.filter(title="The Grammar of Appeal").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_essay, remove_essay),
    ]
