# Generated by Django 6.0.6 on 2026-06-23 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_seed_introduction_essay'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('lesson_plan', 'Lesson Plan'), ('teaching_guide', 'Teaching Guide'), ('strategy', 'Strategy'), ('primary_source_set', 'Primary Source Set'), ('assessment', 'Assessment')], max_length=32)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('url', models.URLField(help_text='Where the resource opens (e.g. on teachinghistory.org).')),
                ('link_label', models.CharField(blank=True, help_text="Optional. Overrides the auto 'Open at <domain>' link text.", max_length=120)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ResourcePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kicker', models.CharField(default='For the Classroom', max_length=120)),
                ('title', models.CharField(default='Educational Resources', max_length=200)),
                ('intro', models.TextField(blank=True, help_text='Markdown. Inline links allowed, e.g. [TeachingHistory.org](https://teachinghistory.org).')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Resources page',
                'verbose_name_plural': 'Resources page',
            },
        ),
    ]
