# Generated by Django 6.0.6 on 2026-06-23 16:25

from django.db import migrations

INTRO = (
    "Lessons, guides, and historical-thinking tools for teaching with "
    "petitions, pension files, and other manuscript records — gathered from "
    "[TeachingHistory.org](https://teachinghistory.org), the National History "
    "Education Clearinghouse at RRCHNM."
)

# The first three cards are taken verbatim from the design mockup. The last
# three use the mockup's visible category labels with sample titles and
# descriptions for the team to replace.
RESOURCES = [
    {
        "category": "lesson_plan",
        "title": "Petitions as Primary Sources",
        "description": (
            "A classroom sequence that uses legislative petitions to teach "
            "students how to source, contextualize, and corroborate a "
            "manuscript document."
        ),
    },
    {
        "category": "teaching_guide",
        "title": "Reading a Pension File",
        "description": (
            "What a Revolutionary War pension declaration can and cannot tell "
            "us — a guide to reading sworn testimony given decades after the "
            "events it describes."
        ),
    },
    {
        "category": "strategy",
        "title": "Reading Like a Historian",
        "description": (
            "The sourcing, contextualization, and close-reading habits that "
            "turn an intimidating old document into evidence students can "
            "actually use."
        ),
    },
    {
        "category": "primary_source_set",
        "title": "Voices from the Pension Office",
        "description": (
            "A curated set of pension declarations, with transcripts and "
            "guiding questions, ready to drop into a document-based lesson."
        ),
    },
    {
        "category": "assessment",
        "title": "Corroboration in Practice",
        "description": (
            "A short performance task that asks students to weigh two "
            "petitions against each other and judge which claim the evidence "
            "better supports."
        ),
    },
    {
        "category": "teaching_guide",
        "title": "Teaching Slavery through the Petition Record",
        "description": (
            "Approaches for using a record built to exclude enslaved "
            "Virginians to teach their presence, carefully and honestly, in "
            "the classroom."
        ),
    },
]


def seed(apps, schema_editor):
    ResourcePage = apps.get_model("pages", "ResourcePage")
    Resource = apps.get_model("pages", "Resource")

    if not ResourcePage.objects.exists():
        ResourcePage.objects.create(
            kicker="For the Classroom",
            title="Educational Resources",
            intro=INTRO,
        )

    if not Resource.objects.exists():
        for i, data in enumerate(RESOURCES):
            Resource.objects.create(
                order=i,
                url="https://teachinghistory.org",
                **data,
            )


def unseed(apps, schema_editor):
    ResourcePage = apps.get_model("pages", "ResourcePage")
    Resource = apps.get_model("pages", "Resource")
    Resource.objects.filter(url="https://teachinghistory.org").delete()
    ResourcePage.objects.filter(title="Educational Resources").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_resource_resourcepage'),
    ]

    operations = [
        migrations.RunPython(seed, unseed),
    ]
