# Generated by Django 6.0.6 on 2026-06-08 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('state', models.CharField(choices=[('VA', 'Virginia'), ('WV', 'West Virginia'), ('KY', 'Kentucky'), ('PA', 'Pennsylvania')], default='VA', max_length=2)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'counties',
                'ordering': ['state', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Petition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField(unique=True)),
                ('mms_id', models.CharField(blank=True, max_length=50)),
                ('rosetta_ie', models.CharField(blank=True, max_length=50, verbose_name='Rosetta IE')),
                ('title', models.CharField(max_length=500)),
                ('petition_type', models.CharField(choices=[('legislative', 'Legislative petition'), ('pension', 'Declaration for Revolutionary War pension')], max_length=20)),
                ('date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('locality_raw', models.CharField(blank=True, help_text='Locality as recorded in the source data', max_length=200, verbose_name='Original locality')),
                ('permalink', models.URLField(blank=True, max_length=500)),
                ('counties', models.ManyToManyField(blank=True, related_name='petitions', to='petitions.county')),
                ('subjects', models.ManyToManyField(blank=True, related_name='petitions', to='petitions.subject')),
            ],
            options={
                'ordering': ['date', 'serial'],
            },
        ),
    ]
