# Generated by Django 6.0.6 on 2026-06-22 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='kind',
            field=models.CharField(blank=True, choices=[('Petition', 'Petition'), ('Remonstrance', 'Remonstrance'), ('Counter-Petition', 'Counter-Petition')], default='Petition', max_length=20),
        ),
        migrations.AddField(
            model_name='petition',
            name='primary_theme',
            field=models.CharField(blank=True, choices=[('property', 'Property & commerce'), ('restrict', 'Restriction & repeal'), ('capital', 'Capital case & loss'), ('freedom', 'Freedom & manumission'), ('estate', 'Estate & property'), ('war', 'Wartime loss')], help_text='Thematic classification for slavery-related petitions', max_length=20),
        ),
    ]
